### ISSUE TITLE
http://jwtbuilder.jamiekurtz.com/tokens is down

### ISSUE THREAD

**Issue by brace110** [jamiekurtz/onlineJwtBuilder#12]
http://jwtbuilder.jamiekurtz.com/tokens is down and returns a 503 server error.

@jamiekurtz Do you have any plans to fix and keep hosting this application?

Kind regards, Brace

**Comment by jamiekurtz** [comment]
/tokens is not a valid path, but [http://jwtbuilder.jamiekurtz.com](http://jwtbuilder.jamiekurtz.com) is up and running
