### ISSUE TITLE
[Security] jwt-simple vulnerable to Authentication Bypass

### ISSUE THREAD

**Issue by mrtouch93** [jamiekurtz/onlineJwtBuilder#7]
Hi Jamies, during a pentest I found a developer who uses your site to generate a jwt token.
Fortunately we are in a test environment, but I think a lot of people using it and the jwt-simple library is vulnerable to an authentication bypass where I can change the algorithm from HS256 to None (here some details: https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/#Meet-the--None--Algorithm).

Do you think is possible to update it? Or at least make a banner with the warning.

Best regards,
Michele

**Comment by jamiekurtz** [comment]
Thank you @mrtouch93 . I will make the necessary updates, as you recommended. Look for an update in the next few days.

**Comment by jamiekurtz** [comment]
@mrtouch93 - all packages have been upgraded and deployed. Thanks again!
